### PR TITLE
feat: display speed status in the notification

### PR DESCRIPTION
**Pull request by Zxilly**
I didn't really test it on my machine. Since I can not build the correct libbox as it expected. It keeps showing `Cannot access 'destroyRef': it is package-private in 'Seq'`

### CODE REVIEW

**Comment by nekohasekai** [comment]
Run `make lib_install` to fix the problem

**Comment by Zxilly** [comment]
I did notice that, but seems singbox using a modified version of gomobile.

**Comment by nekohasekai** [comment]
Your code is relatively primitive. To achieve a standard that can be published to all users, implement:

1. Add a switch for this feature
2. Monitor the screen on and off, and stop updating when the screen goes off.

**Comment by Zxilly** [comment]
I will try to rewrite it

**Pull request closed without merging**
